//const MongoClient = require('mongodb').MongoClient;
const {MongoClient, ObjectID} = require('mongodb'); //this code is identical to the code above. It uses ES6 variable destructuring

//other ES6 desctructuring example
/*
var user = {name: 'andrew', age: 25};
var {name} = user; 
console.log(name);
*/

//new objectid creation (like field _id generated by MongoDB)
/*
var obj = new ObjectID();
console.log(obj);
*/

MongoClient.connect('mongodb://localhost:27017/TodoApp', (err, db) => {
    if (err) {
        return console.log('Unable to connect to MongoDB server');
    }
    console.log('Connected to MongoDB server');

    /*
    //find a document havingt a specific id
    db.collection('Todos').find({
        _id: new ObjectID('59dd7a8eea49e85bd4b9c7fd')
    }).toArray().then( (docs) => {
        console.log('Todos');
        console.log(JSON.stringify(docs, undefined, 2));
    }, (err) => {
            console.log('Unable to fetch todos', err);
    });
    */    
    
   //count number of documents in a collection 
   /*
   db.collection('Todos').find().count().then( (count) => {
        console.log('Todos count: ' + count);
    }, (err) => {
            console.log('Unable to fetch todos', err);
    });   
    */        
        
    db.collection('Users').find({name: /.*Ducas.*/}).toArray().then( (docs) => {
        //console.log('Users Ducas count: ' + count);
        console.log(JSON.stringify(docs, undefined, 2));
    }, (err) => {
            console.log('Unable to fetch todos', err);
    });    
    

    //db.close();
});