//const MongoClient = require('mongodb').MongoClient;
const {MongoClient, ObjectID} = require('mongodb'); //this code is identical to the code above. It uses ES6 variable destructuring

//other ES6 desctructuring example
/*
var user = {name: 'andrew', age: 25};
var {name} = user; 
console.log(name);
*/

//new objectid creation (like field _id generated by MongoDB)
/*
var obj = new ObjectID();
console.log(obj);
*/

MongoClient.connect('mongodb://localhost:27017/TodoApp', (err, db) => {
    if (err) {
        return console.log('Unable to connect to MongoDB server');
    }
    console.log('Connected to MongoDB server');

    /*db.collection('Todos').insertOne({
        text: 'Something to do',
        completed: false
    }, (err, result) => {
        if (err) {
            return console.log('Unable to insert todo', err);
        }

        console.log(JSON.stringify(result.ops, undefined, 2));
    });*/

    //insert new doc into Users (name, age, location)
    /*
    db.collection('Users').insertOne({
        name: 'Marielle Ducas',
        age: 35,
        location: 'Verdun'
    }, (err, result) => {
        if (err) {
            return console.log('Unable to insert User', err);
        }

        console.log(JSON.stringify(result.ops, undefined, 2));
        console.log(result.ops[0]._id.getTimestamp());
    });
    */

    db.close();
});